---
title: "R Notebook"
output: pdf_document
---

```{r}
library(EasyABC)
library(nlrx)
library(tidyverse)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 11),
    axis.title = element_text(size = 13),
    legend.position = "bottom"
  )
theme_set(th)

dir.create("nl")
#download_netlogo("nl/", "6.1.0") # have to manually install

nlobj <- nl(
  nlversion = "6.1.0", 
  nlpath = "nl/NetLogo 6.1.0/", 
  modelpath = "nl/NetLogo 6.1.0/models/Sample Models/Biology/Evolution/Mimicry.nlogo",
  jvmmem = 1024
)
```

```{r}
dir.create("mimcry_results")
nlobj@experiment <- experiment(
  expname = "mimcry",
  outpath = "./mimcry_results/",
  repetition = 1,
  tickmetrics = "true",
  idsetup ="setup",
  idgo ="go",
  runtime = 500,
  evalticks = seq_len(500),
  variables = list(
    "mutation-rate" = list(min = 1, max = 99, qfun = "qunif")
    ),
  constants = list(
    "memory-duration" = 30,
    "memory-size" = 3
  ),
  metrics.turtles = list("turtles" = c("color")),
  metrics = c("count monarchs", "count viceroys")
)
```

```{r}
nlobj@simdesign <- simdesign_lhs(nlobj, samples = 2, nseeds = 1)
print(nlobj)
results <- run_nl_one(nlobj, seed = 1, siminputrow = 1)
```


```{r}
color_shift <- results %>%
  select(`[step]`, starts_with("count"), metrics.turtles) %>%
  unnest(metrics.turtles) %>%
  filter(breed != "birds")
```


```{r}
color_stats <- color_shift %>%
  group_by(breed, `[step]`) %>%
  summarise(
    mean = mean(color),
    sd = sd(color)
  )

ggplot(color_stats, aes(`[step]`, fill = breed, col = breed)) +
  geom_ribbon(aes(`[step]`, ymin = mean - 1.9 * sd, ymax = mean + 1.9 * sd), alpha = 0.3) +
  geom_line(aes(`[step]`, mean))
```

```{r}
nlobj@experiment <- experiment(
  expname = "mimcry",
  outpath = "./mimcry_results/",
  repetition = 1,
  tickmetrics = "true",
  idsetup ="setup",
  idgo ="go",
  runtime = 25,
  evalticks = seq_len(25),
  variables = list(
    "mutation-rate" = list(min = 1, max = 99, qfun = "qunif")
    ),
  constants = list(
    "memory-duration" = 30,
    "memory-size" = 3
  ),
  metrics.turtles = list("turtles" = c("color")),
  metrics = c("count monarchs", "count viceroys")
)
```

```{r}
mutation_model <- function(nlobj) {
  function(rate) {
    nlobj@experiment@variables <- list(
      "mutation-rate" = list(min = rate - 1, max = rate + 1, qfun = "qunif")
      )
    nlobj@simdesign <- simdesign_lhs(nlobj, samples = 1, nseeds = 1)
    results <- run_nl_one(nlobj, seed = 1, siminputrow = 1)
    
    color_stats <- results %>%
      select(`[step]`, starts_with("count"), metrics.turtles) %>%
      unnest(metrics.turtles) %>%
      filter(breed != "birds") %>%
      group_by(breed, `[step]`) %>%
      summarise(mean = mean(color)) %>%
      pivot_wider(names_from = "breed", values_from = "mean") %>%
      mutate(diff = viceroys - monarchs)
    
    coef(lm(diff ~ `[step]`, data = color_stats))[2]
  }
}

prior <- list(c("unif", 0, 100))
m <- mutation_model(nlobj)
test_stat <- m(30)
ABC_mcmc(method = "Marjoram", model = m, prior = prior, summary_stat_target = test_stat, n_calibration = 100)
```

